jeremyevans/roda

lib/roda/plugins/caching.rb
lib/roda/plugins/error_email.rb
lib/roda/plugins/json.rb
lib/roda/plugins/mailer.rb
lib/roda/plugins/path.rb
lib/roda/plugins/render_each.rb
lib/roda/plugins/streaming.rb

This brings most of the plugins into line with the convention already used in chunked, padrino_render, render, and sinatra_helpers.
I couldn't do it in csrf because the hash is immediately passed to Rack::Csrf which seems to want to mutate it.

avoid creating new Hash instances for plugin options where possible

---

lib/roda/plugins/json.rb
spec/plugin/json_spec.rb

Currently the only way to override the JSON conversion is to write something
like this:
```rb
class Roda::RodaRequest
def convert_to_json(object)
end
end
```
So, I thought that instead we could allow the json plugin to accept an additional `:serializer` option:
```rb
plugin :json, serializer: proc { |o| o.to_json(root: true) }
```

Allow the json plugin to accept a serializer

---

www/pages/documentation.erb

I finished my symbolized_params plugin, and I also noticed rom-roda and saw that it wasn't on the list.

Add some external plugins

---

lib/roda/plugins/assets.rb

Noticed the assets plugin was formatting a bit of the docs incorrectly. Think this'll fix it.

trivial indent fix for rdoc

---

lib/roda/plugins/json.rb
lib/roda/plugins/json_parser.rb
spec/plugin/json_parser_spec.rb
spec/plugin/json_spec.rb

When using the json plugin, sometimes we want to serialize the object differently depending on the request headers or request parameters. For example, we might want to give the client the ability to specify which post associations they want returned, with a request like /posts?include=author,comments.
If :include_request=>true is passed to the request, the request object will be passed as the second argument when calling the serializer. We add it to the json_parser plugin as well for consistency.

Add :include_request option for json plugins

---

lib/roda/plugins/multi_run.rb
spec/plugin/multi_run_spec.rb

So it yields with prefix before calling run.
I use it for adding variables to env that gets passed.

allow passing a block to multi_run plugin

---

lib/roda/plugins/middleware.rb
spec/plugin/middleware_spec.rb

The "multi_route" plugin overrides Roda.route and allows it to take arguments. If the "middleware" plugin is loaded after "multi_route", it currently overrides Roda.route with no arguments again. This change allows Roda.route to take any number of arguments, keeping these two plugins compatible.

Make middleware plugin compatible with multi_route

---

lib/roda/plugins/path.rb

I think this should fix the syntax highlighting.

Fix a syntax error in an example comment

---

lib/roda/plugins/caching.rb

Roda doesn't support prepending path string with "/".

Fix an error in the "caching" plugin example

---

lib/roda/plugins/path_rewriter.rb
spec/plugin/path_rewriter_spec.rb

Enhancement for the rewrite_path plugin to enable things like:
rewrite_path %r{\A/foo/(\w+)} {|match| "/foo/#{match[1].downcase}" }

Allow passing a block to rewrite_path plugin for dynamic replacements.

---

lib/roda/plugins/content_for.rb
spec/plugin/content_for_spec.rb

add haml (and maybe others) support for `content_for`. Takes advantage of `content_for`'s dependency on the Render plugin for rendering subsets of views.

ContentFor: Support HAML

---

.gitignore
roda.gemspec

Trying to run this project for the first time (namely the specs) led to errors in the absence of `Rake`
- Adds the `rake` gem to the project's dev dependencies
- Ignores the `Gemfile.lock` which shouldn't ship with a gem anyways.

Helps for first timers

---

lib/roda/plugins/streaming.rb

The standard convention of writable streams is that they respond to `#write`. If we make the stream object respond to `#write`, we could for example use `IO.copy_stream` to efficiently copy a stream to it.
```rb
stream do |out|
IO.copy_stream(StringIO.new(content), out)
end
```

Alias #<< to #write for streaming IO compatibility

---

README.rdoc

Make note of using the unescaping output helper inside layouts when calling `yield`, with the `render` plugin configured with `escape: true`.

Note unescaped yield use in XSS section of README

---

lib/roda/plugins/symbol_status.rb
spec/plugin/symbol_status_spec.rb

This plugin enables response.status= to turn a status name like :ok
into its corresponding HTTP status code.  The behaviour of the method
when being passed a status code as integer is left unchanged.

Add symbol_status plugin for symbolic status names in response.status=

---

lib/roda/plugins/header_matchers.rb

for plugin :header_matchers used like this to just return the value of the header
```ruby
route do |r|
r.on header: 'x-api-version' do |header_value|
header_value
end
end
```
I couldn't get it to match with the default setup, not sure if this is the way to go about fixing it?
Gemfile.lock
```
GEM
remote: https://rubygems.org/
specs:
coderay (1.1.1)
method_source (0.8.2)
mini_portile2 (2.1.0)
pry (0.10.3)
coderay (~> 1.1.0)
method_source (~> 0.8.1)
slop (~> 3.4)
puma (3.4.0)
rack (1.6.4)
rake (11.1.2)
require_all (1.3.3)
roda (2.14.0)
rack
sequel (4.34.0)
slop (3.6.0)
tiny_tds (1.0.4)
mini_portile2 (~> 2.0)
PLATFORMS
ruby
DEPENDENCIES
pry
puma
rake
require_all
roda
sequel
tiny_tds
BUNDLED WITH
1.11.2
```

rack seems to be adding "HTTP_" to all the headers

---

lib/roda/plugins/per_thread_caching.rb

Removes references to the MRI default cache not using a Mutex, since it does now with the 89b9caf commit.

Update MRI cache comments in per_thread_caching plugin

---

www/pages/documentation.erb

Huge apologies, noticed I added the link for this plugin in the documentation to the wrong list; it's in Rendering.
This moves it to Request/Response Helpers.

Move documentation link to the correct list area

---

lib/roda/plugins/extension_response.rb
spec/plugin/extension_response_spec.rb

The extension_response plugin lets the user do routing based on file formats
as requested by a client, both via a "file extension" on the path or via an
Accept request-header.

Add extension_response plugin

---

lib/roda.rb
lib/roda/plugins/public.rb
lib/roda/plugins/type_routing.rb
spec/plugin/type_routing_spec.rb
spec/request_spec.rb

It seems that the type_routing plugin can break the public plugin if the former has a file type defined which we later ask the public plugin to serve. 
With the following app:
```ruby
require 'roda'
class App < Roda
plugin :type_routing, :types => { :png => 'image/png' }
plugin :public
route do |r|
r.public
end
end
run App
```
Assuming that `public/test.png` exists, a 404 is returned. This seems to be because the public plugin is using `remaining_path` and the type_routing plugin has changed it (removed the .png extension). This probably isn't the intended behaviour?

type_routing plugin breaks public plugin

---

lib/roda/plugins/assets.rb

Looks like the Postprocessing docs were nested inside Asset Precompilation which wasn't right.

Postprocessing docs shouldn't be an Asset Precompilation subsection

---

lib/roda.rb
spec/response_spec.rb

Remove Content-Type and Content-Length headers on 204/205/304 responses.

---

www/layout.erb

the "defer" attribute can be used to delay the loading of javascript resources
until the document has been parsed, which avoids blocking the rendering process
of the browser. see "defer" attribute at 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script for more details.
we also use the 'load' event before running any Javascript, so we know at that point
external JS resources have been loaded. please test this locally, as i wasn't able to.
i'm happy to revise if there's any issues. cheers.

defer loading of javascript resource's.

---

lib/roda/plugins/type_routing.rb
spec/plugin/type_routing_spec.rb

I recently ran into a limitation of the type_routing plugin. I was trying to match both ".xml" and ".whatever.xml" as different types, but the ".whatever.xml" type could never be reached.
The commit message below explains the fix. Let me know if you have any questions/comments/feedback.
---
The type_routing plugin previously wouldn't handle extensions containing
the period character. For example, in this app:
class ExampleApp < Roda
plugin :type_routing, types: {
:gz => 'application/octet-stream',
:'tar.gz' => 'application/octet-stream',
}
end
URLs ending in ".tar.gz" would always be detected as the "gz" type,
never the "tar.gz" type.
The commit changes the regex that matches the URL. The group that
captures the "basename" was greedy (by default), meaning that it would capture …

Handle extensions containing dots in type_routing

---

lib/roda/plugins/csrf.rb
spec/plugin/csrf_spec.rb

This pull request will allow the csrf plugin to skip configuring the csrf plugin like this:
```ruby
class App < Roda
plugin :csrf, :skip_middleware=>true
end
```
It helped reduce the csrf middleware duplications.

Skip configuring the CSRF middleware for csrf plugin

---

lib/roda/plugins/sinatra_helpers.rb
lib/roda/plugins/status_303.rb
spec/plugin/status_303_spec.rb

The implementation was pulled out of sinatra_helpers, which now depends
on the status_303 plugin.

Add status_303 plugin for lovers of RFC 7231

---

README.rdoc

Rack::Request#[] is deprecated and Roda should avoid using it in its documentation.

Remove usage of deprecated request#[] in README

---

lib/roda/plugins/route_csrf.rb

Because the options are currently indented, they get interpreted as a raw block of code. This PR should fix this.

Fix options documentation in route_csrf RDocs

---

www/pages/index.erb
www/public/css/roda.css

One of the header tags was improperly closed at the bottom of the home page.
Paragraph styling felt a little odd in the comparison section.
Very small tweaks. This looks ready for deployment to me.

Fix broken html tag on home page and update compare styling

---

roda.gemspec

As defined in https://guides.rubygems.org/specification-reference/
Somebody recently sent a PR to categorize roda on the Ruby Toolbox (see https://github.com/rubytoolbox/catalog/pull/175), and I noticed the library does not have a proper linking to it's github repo and therefore is missing all github-related stats:
By adding it to the gemspec (and releasing ;) the proper linking should be picked up, and users will also be able to go to the github repo from rubygems.org directly as well.

Add source code URI to gemspec

---

lib/roda/plugins/yield_response.rb
spec/plugin/yield_response_spec.rb
www/pages/documentation.erb

The `yield_response` plugin adds the RodaResponse instance as an optional second argument to the `route` block, which makes the route block's signature match that of express.js and Node's default HTTP server. The aim is to make it easier to see that the response is in scope, and to make Roda more intuitive to developers coming from Node.
```ruby
class App < Roda
plugin :yield_response
route do |req, res|
res.status = 203
res.write = "Hello, #{req.params['name']}"
end
end
```

Add yield_response plugin

---

lib/roda/plugins/route_block_args.rb

In the inline documentation re: configuring the route_block_args plugin, I think the example needs to call `request.params` instead `params`.

Fix typo in route_block_args example

---

lib/roda/plugins/sessions.rb
spec/plugin/sessions_spec.rb

This allows the `clear_session` to be called from any child path, resolving #162

Add cookie options to Set-Cookie when removing cookie

---

lib/roda/plugins/match_hook.rb
spec/plugin/match_hook_spec.rb
www/pages/documentation.erb

Adds the `match_hook` plugin, allowing a block (or multiple) to be called on each successful match of the routing tree.

Add match_hook plugin

---

lib/roda/plugins/sessions.rb

The option should be `:max_idle_seconds` instead of `:max_idle_sessions`

Fix typo in the Sessions plugin documentation

---

lib/roda/plugins/assets.rb

The assets plugin produced incorrect code (e.g. in JS) when two consecutive assets present the following conditions:
1) the first file ends with a _line_ comment, such as a `//` comment in JS
2) the first file does not end with a newline character sequence
3) the second file starts with a comment block, such as `/*` in JS
Can be seen with bootstrap.min.js and holder.min.js:
Notice at the end of line 9 that holder.js' comment block start gets commented out by Bootstrap's trailing comment line.

Incorrect assets plugin output on comments edge case

---

lib/roda/plugins/run_append_slash.rb
spec/plugin/run_append_slash_spec.rb

If run_handler plugin was loaded before run_append_slash plugin,
Request#run wouldn't accept multiple arguments anymore, so one for
example wouldn't be able to pass `not_found: :pass`. We fix that by
forwarding any number of arguments in run_handler plugin.

Make run_append_slash work with run_handler

---

doc/release_notes/3.3.0.txt
lib/roda/plugins/typecast_params.rb

Hello! I found this tiny typo in the `typecast_params` plugin documentation. That's it <3

fix typo in typecast_params documentation

---

.github/workflows/ci.yml

TruffleRuby was uninentionally removed in https://github.com/jeremyevans/roda/commit/e88ecf456d4df93b8ab0b28d41a9b1298b18b86f#commitcomment-44571643, this adds it back.
I also took the opportunity to clean up a bit the ci.yml.

CI cleanups and re-add truffleruby-head to CI

---

lib/roda/plugins/common_logger.rb
spec/plugin/common_logger_spec.rb

Makes it possible to let common_logger call a user defined method like :debug, instead of the default :write or :<<

Add common_logger_meth as a plugin option

---

lib/roda.rb
spec/plugin/middleware_spec.rb

The previous approach wasn't working in Ruby v3 for middleware which use keyword arguments.
I'm making use of the existing `_define_roda_method_arg_numbers` method and `RUBY_VERSION` checks to ensure the final hash argument is only translated into keyword arguments if appropriate. I've no experience of the Roda source though, so do let me know if there's a better way to handle all of this!

Allow for middleware with keyword arguments.

---

lib/roda/plugins/content_for.rb

The default behavior (append mode) is already mentioned in the module docs so I figured we might as well remove the sentence entirely.
Thanks for the awesome libraries Jeremy!

Remove inaccurate comment in content_for plugin

---

lib/roda/plugins/middleware.rb

In https://github.com/jeremyevans/roda/pull/259, I forgot to update documentation with the new `:forward_response_headers` option for the middleware plugin, so I'm adding it here.

Document `:forward_response_headers` middleware plugin option

---

lib/roda/plugins/halt.rb

This makes RDoc properly highlight that code block.

Fix syntax in halt plugin example

---

lib/roda/plugins/mail_processor.rb
lib/roda/plugins/typecast_params.rb

Found by carefully reading the documentation of `typecast_params` plugin.
Thanks!

Fix typo in doc-sctrings

---

.github/workflows/ci.yml
lib/roda/plugins/exception_page.rb
spec/plugin/exception_page_spec.rb

* See https://github.com/oracle/truffleruby/issues/3257
This is necessary so that roda works on the upcoming 23.1 release (it's too late to implement `Exception#detailed_message` there, we are past the last bug fix deadline).

Use feature detection to find out if detailed_message is available

---

lib/roda/plugins/middleware.rb
spec/plugin/middleware_spec.rb

By default it's an anonymous subclass, which doesn't communicate connection to the Roda app in the inspect output. In [rodauth-rails](https://github.com/janko/rodauth-rails/blob/7f6cd886d3af5680bf349e61941f728e5a580ff5/lib/rodauth/rails/app.rb#L10-L16), I overrode `inspect` to provide some context.
Ruby 3.3 added [`Module#set_temporary_name`](https://docs.ruby-lang.org/en/master/Module.html#method-i-set_temporary_name), which we can use to improve introspection.

Set temporary name for middleware subclass

---

lib/roda/plugins/plain_hash_response_headers.rb

The name of the plugin is `plain_hash_response_headers`.

Use correct plugin name in documentation

---

lib/roda/plugins/early_hints.rb

Updated `early_hints` plugin documentation to remove a caveat about only Puma supporting 103 Early Hints. I think the caveat can be dropped now that folk are using newer versions of Puma and Falcon and Pitchfork have added Early Hints support.

Remove `early_hints` plugin limited support caveat

---

.github/workflows/ci.yml

Don't you mind adding TruffleRuby back as far as specs are passing now?
TruffleRuby CI was removed in 2bb51f46150c0a477b697f09b42efa29b947941a.

Restore TruffleRuby CI

---

lib/roda/plugins/assets.rb

I checked the codebase and chose "it is" over "it's" as it seems to be more in line with your style.
(In this file, there are 7 instances of "it is" and 0 of "it's." In the entire repo, Github has indexed 80 files containing at least one instance of "it is" and 18 files containing at least one instance of "it's.")

Correct typo "it" -> "it is"
